### ISSUE TITLE
Abbiamo perso CloudItaly

### ISSUE THREAD

**Issue by nastasi** [JCN-9000/MiniEPG#11]
Ciao, clouditaly.tk è perso, qualche idea su cosa usare come rimpiazzo ?
Saluti e grazie.

**Comment by JCN-9000** [comment]
Per ora uno dei due link nel file che viene scaricato da clouditaly.tk è ancora valido.
Ho quindi inserito lo zip file nel pacchetto e dovrebbe sopperire.
Scaricate manualmente:  [files_crossepg_last.zip](https://github.com/JCN-9000/MiniEPG/raw/master/files_crossepg_last.zip) nella cartella MiniEPG
La procedura, se si trova il file, non tenta di scaricarlo nuovamente.
