### ISSUE TITLE
Richiesta di aiuto per MiniEPG per Blobbox

### ISSUE THREAD

**Issue by clabac** [JCN-9000/MiniEPG#12]
Salve, sono entrato oggi in GitHub per la prima volta e non vorrei fare troppa confusione, pero' ho installato una macchina virtuale VirtualBox Linux Lite 3.0 e ho provato a caricarvi il progetto MiniEPG.
Non riesco a ottenere il file finale epg.v2.sqlite, ma e' sicuramente un errore mio da da qualche parte.
Allego i messaggi del terminale, che spero diano qualche indicazione.
![clipboard02](https://cloud.githubusercontent.com/assets/19778969/15824834/6b804082-2c01-11e6-9f74-95442f0806b0.png)
Grazie per l'attenzione
Clabac

**Comment by JCN-9000** [comment]
Ciao
ti mancano alcuni pezzi:
- `/usr/bin/sqlite3: Is a directory`   indica che sqlite3 non è installato correttamente.
  Soluzione: Verifica ( non facile ) che sia installato correttamente - Prova a disinstallarlo e reinstallarlo.
-  `ImportError: No module named dateutil`   indica che manca un modulo di Python. Occorre aggiungerlo con `sudo apt-get install python-dateutil` .

Segui comunque le indicazioni della tua distribuzione per fare queste operazioni

**Comment by clabac** [comment]
Ciao,
grazie per la rapida risposta.
Il problema di sqlite3 l'ho visto e risolto poco fa, in effetti non 
avevo installato l'eseguibile nella cartella giusta, ma avevo copiato la 
cartella espansa .... ho veramente poca esperienza su Linux !
Non ho cambiato lo script.

Domani provero' a controllare il modulo Python, le tue indicazioni mi 
sembrano complete.

Sto provando a installare un server web, tipo Apache.
Mi sembra un discreto impegno, ma ho fiducia.
Stavo pensando di installarlo direttamente sulla macchina virtuale Linux.

Grazie ancora e buona serata.
Claudio

Il 06/06/2016 20.19, JCN-9000 ha scritto:

**Comment by clabac** [comment]
Ciao, ho installato il modulo python dateutil, e adesso mi ritrovo con un altro errore ....

osboxes@osboxes:~/Desktop/MiniEPG$ bash MiniEPG.sh
Download EPG da CloudItaly
Traceback (most recent call last):
  File "XMLTV_EPG.py", line 13, in <module>
    import pytz
ImportError: No module named pytz
updating: epg.v2.sqlite (deflated 81%)

Non vorrei diventare un incubo, ma non so  proprio dove cercare la soluzione ...
Grazie per la pazienza
Claudio

**Comment by JCN-9000** [comment]
Altro modulo python non installato di default.
Installa `python-tz` , spero che si chiami così anche su Linux Lite.
Descrizione: _Python version of the Olson timezone database_
P.S. per ora sono i due moduli indicati nel file [INSTALL](../blob/master/INSTALL)

**Comment by clabac** [comment]
Grazie !

**Comment by clabac** [comment]
Mancava anche unidecode, ma sono riuscito a trovarlo ....
Adesso vedo che scorre la lista dei canali e il file finale viene prodotto.
Ho installato apache2, mi resta "solo" di configurarlo per avere un web server locale.
Ho visto un po' di documentazione in giro, sara' il lavoro di domani.
Ti ringrazio ancora e chiuderei qui l'issue.
Buona serata

**Comment by JCN-9000** [comment]
Forse [nginx](http://nginx.org/) è più leggero per una macchina virtuale e penso anche più facile da configurare per un principiante. La configurazione di default di Apache dovrebbe comunque permetterti di servire il file quasi senza modifiche.
Attenzione che raggiungere una macchina virtuale dall'esterno non è semplicissimo. Leggiti bene le istruzioni per la gestione della rete.
